/**
 * Generated by `npm run shopify:variant-ids`. Do not edit by hand.
 *
 * Shopify `ProductVariant` GIDs keyed by the `id` in products.json, which
 * is written to Shopify as the variant SKU. Regenerate after adding or
 * recreating a product -- deleting and re-adding a product in Shopify mints a
 * new variant ID, and a stale one here is a cart line that fails to add.
 *
 * `href` rides along so the cart can link a line back to its product page
 * without importing the catalog. The cart is a client component, and pulling
 * in products.json to resolve 34 URLs would ship every description, feature
 * list and review to the browser to render a list of links.
 *
 * Deliberately carries no timestamp: a generated-at line would make this file
 * churn on every run and bury the one thing worth reading in a diff, which is
 * whether an ID changed.
 */

export type GeneratedVariant = {
  variantId: string;
  href: string;
};

export const GENERATED_VARIANTS: Readonly<Record<string, GeneratedVariant>> = {
  "chair-mesh-004": { variantId: "gid://shopify/ProductVariant/50509101990123", href: "/chairs/neuro-mesh-chair/" },
  "chair-mesh-005": { variantId: "gid://shopify/ProductVariant/50509108478187", href: "/chairs/zynx-mesh-chair/" },
  "chair-mesh-006": { variantId: "gid://shopify/ProductVariant/50509108674795", href: "/chairs/xyron-mesh-chair/" },
  "chair-leather-002": { variantId: "gid://shopify/ProductVariant/50509108871403", href: "/chairs/rider-leather-chair/" },
  "chair-leather-003": { variantId: "gid://shopify/ProductVariant/50509109068011", href: "/chairs/nexor-leather-chair/" },
  "chair-leather-005": { variantId: "gid://shopify/ProductVariant/50509109166315", href: "/chairs/valerio-leather-chair/" },
  "chair-fabric-001": { variantId: "gid://shopify/ProductVariant/50509109264619", href: "/chairs/fabio-fabric-chair/" },
  "chair-fabric-003": { variantId: "gid://shopify/ProductVariant/50509109330155", href: "/chairs/casca-fabric-chair/" },
  "chair-fabric-005": { variantId: "gid://shopify/ProductVariant/50509109395691", href: "/chairs/niyo-fabric-chair/" },
  "table-bed-003": { variantId: "gid://shopify/ProductVariant/50509109461227", href: "/tables/flexon-bed-table/" },
  "table-folding-002": { variantId: "gid://shopify/ProductVariant/50509109526763", href: "/tables/exquisite-primex-folding-table/" },
  "table-folding-004": { variantId: "gid://shopify/ProductVariant/50509109592299", href: "/tables/nextable-folding-table/" },
  "table-height-adjustable-002": { variantId: "gid://shopify/ProductVariant/50509109625067", href: "/tables/modura-height-adjustable-table/" },
  "table-height-adjustable-003": { variantId: "gid://shopify/ProductVariant/50509109657835", href: "/tables/modura-primex-height-adjustable-table/" },
  "table-height-adjustable-005": { variantId: "gid://shopify/ProductVariant/50509109723371", href: "/tables/modulus-primex-height-adjustable-table/" },
  "table-height-adjustable-006": { variantId: "gid://shopify/ProductVariant/50509109756139", href: "/tables/movix-height-adjustable-table/" },
  "table-executive-003": { variantId: "gid://shopify/ProductVariant/50509110411499", href: "/tables/imperium-executive-table/" },
  "table-executive-004": { variantId: "gid://shopify/ProductVariant/50509110477035", href: "/tables/signature-executive-table/" },
  "table-study-003": { variantId: "gid://shopify/ProductVariant/50509110509803", href: "/tables/zenith-study-table/" },
  "table-study-006": { variantId: "gid://shopify/ProductVariant/50509110542571", href: "/tables/zenvy-primex-study-table/" },
  "table-gaming-desk-001": { variantId: "gid://shopify/ProductVariant/50509110575339", href: "/tables/quantum-gaming-desk/" },
  "table-gaming-desk-002": { variantId: "gid://shopify/ProductVariant/50509110608107", href: "/tables/quantum-primex-gaming-desk/" },
  "accessories-storage-box-002": { variantId: "gid://shopify/ProductVariant/50509110640875", href: "/accessories/storage-box-plus/" },
  "accessories-storage-box-004": { variantId: "gid://shopify/ProductVariant/50509110706411", href: "/accessories/storage-box-pro-max/" },
  "accessories-footrest-001": { variantId: "gid://shopify/ProductVariant/50509110739179", href: "/accessories/footrest-basic/" },
  "accessories-footrest-002": { variantId: "gid://shopify/ProductVariant/50509110771947", href: "/accessories/footrest-plus/" },
  "accessories-cable-tray-001": { variantId: "gid://shopify/ProductVariant/50509110804715", href: "/accessories/cable-tray-basic/" },
  "accessories-Cpu-Stand-002": { variantId: "gid://shopify/ProductVariant/50509110837483", href: "/accessories/cpu-stand-plus/" },
  "accessories-Cpu-Stand-003": { variantId: "gid://shopify/ProductVariant/50509110870251", href: "/accessories/cpu-stand-pro/" },
  "accessories-monitor-stand-001": { variantId: "gid://shopify/ProductVariant/50509110903019", href: "/accessories/monitor-stand-basic/" },
  "accessories-monitor-stand-004": { variantId: "gid://shopify/ProductVariant/50509111460075", href: "/accessories/monitor-stand-pro-max/" },
  "accessories-cup-holder-001": { variantId: "gid://shopify/ProductVariant/50509111525611", href: "/accessories/cup-holder-basic/" },
  "accessories-desk-hook-001": { variantId: "gid://shopify/ProductVariant/50509111558379", href: "/accessories/desk-hook-basic/" },
  "accessories-desk-hook-002": { variantId: "gid://shopify/ProductVariant/50509111591147", href: "/accessories/desk-hook-plus/" },
};
