/**
 * Generates `src/lib/variant-ids.generated.ts`.
 *
 * The Cart API is variant-bound: `cartLinesAdd` takes a `merchandiseId`,
 * which is a `ProductVariant` GID minted by Shopify when the product was
 * created. It cannot be derived from products.json and it cannot be guessed,
 * so it has to be read back out of the store and committed.
 *
 * ## Why this reads the Storefront API rather than the Admin API
 *
 * Both return the same variant, but not necessarily in the same shape -- the
 * Storefront API has historically handed back base64 IDs where Admin hands
 * back plain GIDs. Reading from the exact API the browser will call makes the
 * IDs correct by construction rather than correct by assumption.
 *
 * It also means this script needs no credentials, and it only sees what a
 * customer sees: a product that is missing here is a product that is missing
 * from the storefront, which is a finding rather than a nuisance.
 *
 *   npx tsx scripts/shopify/variant-ids.ts
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { allProducts } from "../../src/lib/catalog";
import { storefront } from "../../src/lib/shopify";

const OUT = join(process.cwd(), "src", "lib", "variant-ids.generated.ts");

type Node = {
  handle: string;
  title: string;
  variants: {
    nodes: {
      id: string;
      sku: string | null;
      price: { amount: string } | null;
      compareAtPrice: { amount: string } | null;
    }[];
  };
};

type Page = {
  products: {
    pageInfo: { hasNextPage: boolean; endCursor: string | null };
    nodes: Node[];
  };
};

const QUERY = `
  query VariantIds($cursor: String) {
    products(first: 100, after: $cursor) {
      pageInfo { hasNextPage endCursor }
      nodes {
        handle
        title
        variants(first: 50) {
          nodes {
            id
            sku
            price { amount }
            compareAtPrice { amount }
          }
        }
      }
    }
  }
`;

async function fetchAll(): Promise<Node[]> {
  const all: Node[] = [];
  let cursor: string | null = null;

  for (;;) {
    const page: Page = await storefront<Page>(QUERY, { cursor });
    all.push(...page.products.nodes);
    if (!page.products.pageInfo.hasNextPage) break;
    cursor = page.products.pageInfo.endCursor;
  }

  return all;
}

type Entry = {
  sku: string;
  variantId: string;
  href: string;
  /**
   * The printed MRP as Shopify holds it, in paise. Absent when no compare-at
   * price is set on the variant, which is the correct state for anything not
   * on offer -- the site then shows a plain price with no saving claimed.
   */
  comparePaise?: number;
};

function render(entries: Entry[]): string {
  const rows = entries
    .map(
      (e) =>
        `  ${JSON.stringify(e.sku)}: { variantId: ${JSON.stringify(
          e.variantId,
        )}, href: ${JSON.stringify(e.href)}${
          e.comparePaise ? `, comparePaise: ${e.comparePaise}` : ""
        } },`,
    )
    .join("\n");

  return `/**
 * Generated by \`npm run shopify:variant-ids\`. Do not edit by hand.
 *
 * Shopify \`ProductVariant\` GIDs keyed by the variant \`id\` in products.json,
 * which is written to Shopify as the variant SKU. Regenerate after adding or
 * recreating a product -- deleting and re-adding a product in Shopify mints a
 * new variant ID, and a stale one here is a cart line that fails to add.
 *
 * One entry per colourway, not per product, so a product whose black synced
 * and whose white did not still sells in black.
 *
 * \`href\` rides along so the cart can link a line back to its product page
 * without importing the catalog. The cart is a client component, and pulling
 * in products.json to resolve these URLs would ship every description, feature
 * list and review to the browser to render a list of links.
 *
 * \`comparePaise\` is the printed MRP, read back from Shopify rather than
 * stored in this repo. Shopify is the source of truth for it: change a
 * compare-at price in the admin, re-run this script, and the site follows. A
 * variant with no compare-at price simply has no key here and renders a plain
 * price, so removing an offer needs no code change.
 *
 * Deliberately carries no timestamp: a generated-at line would make this file
 * churn on every run and bury the one thing worth reading in a diff, which is
 * whether an ID changed.
 */

export type GeneratedVariant = {
  variantId: string;
  href: string;
  comparePaise?: number;
};

export const GENERATED_VARIANTS: Readonly<Record<string, GeneratedVariant>> = {
${rows}
};
`;
}

async function main() {
  const local = allProducts;
  const remote = await fetchAll();

  const bySku = new Map<
    string,
    { id: string; pricePaise: number | null; comparePaise: number | null }
  >();
  const problems: string[] = [];

  /**
   * Shopify returns money as a decimal string ("18999.00"). Parsing to paise
   * via a float multiply is the usual way to lose a rupee to binary rounding,
   * so round after scaling rather than trusting the product.
   */
  const toPaise = (amount: string | null | undefined): number | null => {
    if (!amount) return null;
    const value = Math.round(Number(amount) * 100);
    return Number.isFinite(value) && value > 0 ? value : null;
  };

  for (const node of remote) {
    const variants = node.variants.nodes;

    /*
     * The September 2026 range made colour a real Shopify option, so a product
     * carries one variant per colourway rather than a single implicit "Default
     * Title". Every variant is keyed independently by its SKU, which is the
     * variant `id` from products.json -- that is what the cart looks up, and
     * it lets the site degrade one colourway at a time rather than dropping a
     * whole product because one finish failed to sync.
     */
    if (variants.length === 0) {
      problems.push(`${node.handle}: no variants`);
      continue;
    }

    for (const variant of variants) {
      if (!variant.sku) {
        problems.push(
          `${node.handle}: a variant has no SKU, cannot be keyed`,
        );
        continue;
      }

      const clash = bySku.get(variant.sku);
      if (clash && clash.id !== variant.id) {
        problems.push(`SKU ${variant.sku} is on two variants`);
        continue;
      }

      bySku.set(variant.sku, {
        id: variant.id,
        pricePaise: toPaise(variant.price?.amount),
        comparePaise: toPaise(variant.compareAtPrice?.amount),
      });
    }
  }

  /*
   * Only ship IDs for variants the site actually renders, in catalog order so
   * the diff stays stable rather than following Shopify's pagination. Every
   * colourway of a product shares one product page: the picker is client-side
   * state, not a URL parameter, so `href` is the product href for all of them.
   */
  const entries: Entry[] = [];
  const missing: string[] = [];
  const priceDrift: string[] = [];
  const noCompareAt: string[] = [];

  for (const product of local) {
    for (const variant of product.variants) {
      const remoteVariant = bySku.get(variant.id);
      if (!remoteVariant) {
        missing.push(`${variant.id} (${product.slug})`);
        continue;
      }

      /*
       * The site prints the price from products.json but Shopify is what
       * actually charges the customer. A silent divergence between the two is
       * the one pricing bug nobody notices until an order arrives at the
       * wrong total, so it is worth a line of arithmetic to catch.
       */
      if (
        remoteVariant.pricePaise !== null &&
        remoteVariant.pricePaise !== variant.pricePaise
      ) {
        priceDrift.push(
          `${variant.id}: site ${variant.pricePaise / 100}, Shopify ${
            remoteVariant.pricePaise / 100
          }`,
        );
      }

      // A compare-at price at or below the selling price claims a saving that
      // does not exist. Shopify permits it; the site must not repeat it.
      const compare =
        remoteVariant.comparePaise !== null &&
        remoteVariant.comparePaise > variant.pricePaise
          ? remoteVariant.comparePaise
          : undefined;

      if (compare === undefined) noCompareAt.push(variant.id);

      entries.push({
        sku: variant.id,
        variantId: remoteVariant.id,
        href: product.href,
        ...(compare ? { comparePaise: compare } : {}),
      });
    }
  }

  writeFileSync(OUT, render(entries), "utf8");

  console.log(`storefront products : ${remote.length}`);
  console.log(
    `local catalog       : ${local.length} product(s), ${local.reduce(
      (n, p) => n + p.variants.length,
      0,
    )} variant(s)`,
  );
  console.log(`variant IDs written : ${entries.length}`);
  console.log(
    `with an MRP         : ${entries.filter((e) => e.comparePaise).length}`,
  );
  console.log(`-> ${OUT}`);

  if (noCompareAt.length) {
    console.log(`\nno MRP in Shopify (${noCompareAt.length}), will show a plain price:`);
    for (const sku of noCompareAt) console.log(`  ${sku}`);
  }

  if (priceDrift.length) {
    console.log(`\nPRICE DRIFT (${priceDrift.length}) -- site and Shopify disagree:`);
    for (const line of priceDrift) console.log(`  ${line}`);
  }

  if (missing.length) {
    console.log(`\nnot purchasable (${missing.length}):`);
    for (const sku of missing) console.log(`  ${sku}`);
  }

  if (problems.length) {
    console.log(`\nproblems (${problems.length}):`);
    for (const problem of problems) console.log(`  ${problem}`);
  }

  // A partial map is a valid state -- the site degrades per product, showing
  // an enquiry form for anything without an ID. It is not a valid state to
  // discover silently, so say so loudly and let the caller decide. Price drift
  // is never acceptable and fails on its own.
  if (missing.length || problems.length || priceDrift.length) {
    process.exitCode = 1;
  }
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : error);
  process.exit(1);
});
